//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zvonochek.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        public int Id { get; set; }
        public Nullable<int> Id_Client { get; set; }
        public Nullable<int> Id_Phone { get; set; }
        public Nullable<int> Id_StatusAplication { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Phone Phone { get; set; }
        public virtual StatusAplication StatusAplication { get; set; }
    }
}
