//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zvonochek.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class WarehouseCons
    {
        public int Id { get; set; }
        public Nullable<int> Id_Cons { get; set; }
        public Nullable<int> value { get; set; }
    
        public virtual Consumables Consumables { get; set; }
    }
}
