//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zvonochek.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ZvonochekEntities : DbContext
    {
        public ZvonochekEntities()
            : base("name=ZvonochekEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Application> Application { get; set; }
        public virtual DbSet<CategoryRepair> CategoryRepair { get; set; }
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Consumables> Consumables { get; set; }
        public virtual DbSet<Employe> Employe { get; set; }
        public virtual DbSet<Money> Money { get; set; }
        public virtual DbSet<Phone> Phone { get; set; }
        public virtual DbSet<PhoneType> PhoneType { get; set; }
        public virtual DbSet<Post> Post { get; set; }
        public virtual DbSet<RepairCertificate> RepairCertificate { get; set; }
        public virtual DbSet<StatusAplication> StatusAplication { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<WarehouseCons> WarehouseCons { get; set; }
    }
}
